#!/bin/sh
### BEGIN INIT INFO
# Provides:          picommand
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts PiCommand
# Description:       starts PiCommand using start-stop-daemon
### END INIT INFO


case "$1" in
start)

    . /home/pi/PiCommand/bin/activate
    start-stop-daemon --start --exec /home/pi/PiCommand/bin/gunicorn -- -D -b 0.0.0.0:8000 --pythonpath /home/pi/PiCommand/PiCommand command:application
        
;;

stop)
    

;;

restart)

    start-stop-daemon --stop --exec /home/pi/PiCommand/bin/python /home/pi/PiCommand/bin/gunicorn
    . /home/pi/PiCommand/bin/activate
    start-stop-daemon --start --exec /home/pi/PiCommand/bin/gunicorn -- -D -b 0.0.0.0:8000 --pythonpath /home/pi/PiCommand/PiCommand command:application

;;

esac
exit 0
